package com.example.modelviewwhateverpractice.datamodel;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import com.example.modelviewwhateverpractice.repository.localrepository.ItemDbConstants;

import java.util.Objects;

/**
 * Deleting the Kotlin data class because I am using Room.
 * I'll deal with Room and Kotlin down-the-road.
 */
@Entity(tableName = ItemDbConstants.ITEM_TABLE)
public final class Item {

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = ItemDbConstants.COLUMN_ID)
    private int id;

    @ColumnInfo(name = ItemDbConstants.COLUMN_TITLE)
    private final String title;

    public Item(int id, String title) {
        this.id = id;
        this.title = title;
    }

    @Ignore
    public Item(String title) {
        this.title = title;
    }


    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }


    /**
     * Generated by Android Studio.
     */

    @Override
    public String toString() {
        return "Item{" +
                "id=" + id +
                ", title='" + title + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Item item = (Item) o;
        return getId() == item.getId() &&
                getTitle().equals(item.getTitle());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getTitle());
    }
}
